server:
  port: 9999

spring:
  application:
    name: managementservice
  datasource:
    url: jdbc:postgresql://localhost:5432/event
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true