server:
  port: 8081

spring:
  application:
    name: managementservice
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/event
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver

  datasource:
    url: jdbc:mysql://localhost:3306/event
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true